spring:
  application:
    name: eureka-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
